levels:
  - # Business logic. Workers, handlers, complex processing.
    - 'worker'
    - 'handler'

  - # Simple components. Straightforward task components, helpers, connectors.
    - 'fetcher'
    - 'saver'

  - # Trivial components. External package wrappers, common primitives, tools.
    - 'db/io'
    - 'http'
